# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    if: "!contains(github.event.head_commit.message, '[--skip build]')"

    strategy:
      matrix:
        node-version: [14.15.1]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Build Use Node.js ${{ matrix.node-version }}

    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: git branch 
    
    - uses: EndBug/add-and-commit@v7
      with:
        add: '.'
        author_name: github_actor
        author_email: platform@ilark.co.kr
        default_author: github_actor
        message: 'BUILD HTMLS -- skip build'
        push: true
